export * from './admins-page'
export * from './users-page'
export * from './investments-page'
export * from './home-page'
export * from './profile-page'
export * from './new-user-page'
export * from './admins-page'
export * from './edit-admin.page'