/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as UsersImport } from './routes/users'
import { Route as ReportsImport } from './routes/reports'
import { Route as RegisterImport } from './routes/register'
import { Route as ProfileImport } from './routes/profile'
import { Route as PlanImport } from './routes/plan'
import { Route as LoginImport } from './routes/login'
import { Route as InvestmentsImport } from './routes/investments'
import { Route as InvestImport } from './routes/invest'
import { Route as HomeImport } from './routes/home'
import { Route as FinancesImport } from './routes/finances'
import { Route as AdminsImport } from './routes/admins'
import { Route as IndexImport } from './routes/index'
import { Route as UsersNewImport } from './routes/users.new'
import { Route as UserReportImport } from './routes/user.report'
import { Route as FinancesNewImport } from './routes/finances.new'
import { Route as FinancesEditImport } from './routes/finances.edit'
import { Route as AdminsNewImport } from './routes/admins.new'
import { Route as UsersUserIdEditImport } from './routes/users.$userId.edit'
import { Route as AdminsUserIdEditImport } from './routes/admins.$userId.edit'

// Create/Update Routes

const UsersRoute = UsersImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRoute,
} as any)

const ReportsRoute = ReportsImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRoute,
} as any)

const RegisterRoute = RegisterImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRoute,
} as any)

const ProfileRoute = ProfileImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRoute,
} as any)

const PlanRoute = PlanImport.update({
  id: '/plan',
  path: '/plan',
  getParentRoute: () => rootRoute,
} as any)

const LoginRoute = LoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const InvestmentsRoute = InvestmentsImport.update({
  id: '/investments',
  path: '/investments',
  getParentRoute: () => rootRoute,
} as any)

const InvestRoute = InvestImport.update({
  id: '/invest',
  path: '/invest',
  getParentRoute: () => rootRoute,
} as any)

const HomeRoute = HomeImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRoute,
} as any)

const FinancesRoute = FinancesImport.update({
  id: '/finances',
  path: '/finances',
  getParentRoute: () => rootRoute,
} as any)

const AdminsRoute = AdminsImport.update({
  id: '/admins',
  path: '/admins',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const UsersNewRoute = UsersNewImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => UsersRoute,
} as any)

const UserReportRoute = UserReportImport.update({
  id: '/user/report',
  path: '/user/report',
  getParentRoute: () => rootRoute,
} as any)

const FinancesNewRoute = FinancesNewImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => FinancesRoute,
} as any)

const FinancesEditRoute = FinancesEditImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => FinancesRoute,
} as any)

const AdminsNewRoute = AdminsNewImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AdminsRoute,
} as any)

const UsersUserIdEditRoute = UsersUserIdEditImport.update({
  id: '/$userId/edit',
  path: '/$userId/edit',
  getParentRoute: () => UsersRoute,
} as any)

const AdminsUserIdEditRoute = AdminsUserIdEditImport.update({
  id: '/$userId/edit',
  path: '/$userId/edit',
  getParentRoute: () => AdminsRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/admins': {
      id: '/admins'
      path: '/admins'
      fullPath: '/admins'
      preLoaderRoute: typeof AdminsImport
      parentRoute: typeof rootRoute
    }
    '/finances': {
      id: '/finances'
      path: '/finances'
      fullPath: '/finances'
      preLoaderRoute: typeof FinancesImport
      parentRoute: typeof rootRoute
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeImport
      parentRoute: typeof rootRoute
    }
    '/invest': {
      id: '/invest'
      path: '/invest'
      fullPath: '/invest'
      preLoaderRoute: typeof InvestImport
      parentRoute: typeof rootRoute
    }
    '/investments': {
      id: '/investments'
      path: '/investments'
      fullPath: '/investments'
      preLoaderRoute: typeof InvestmentsImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/plan': {
      id: '/plan'
      path: '/plan'
      fullPath: '/plan'
      preLoaderRoute: typeof PlanImport
      parentRoute: typeof rootRoute
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileImport
      parentRoute: typeof rootRoute
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterImport
      parentRoute: typeof rootRoute
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsImport
      parentRoute: typeof rootRoute
    }
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersImport
      parentRoute: typeof rootRoute
    }
    '/admins/new': {
      id: '/admins/new'
      path: '/new'
      fullPath: '/admins/new'
      preLoaderRoute: typeof AdminsNewImport
      parentRoute: typeof AdminsImport
    }
    '/finances/edit': {
      id: '/finances/edit'
      path: '/edit'
      fullPath: '/finances/edit'
      preLoaderRoute: typeof FinancesEditImport
      parentRoute: typeof FinancesImport
    }
    '/finances/new': {
      id: '/finances/new'
      path: '/new'
      fullPath: '/finances/new'
      preLoaderRoute: typeof FinancesNewImport
      parentRoute: typeof FinancesImport
    }
    '/user/report': {
      id: '/user/report'
      path: '/user/report'
      fullPath: '/user/report'
      preLoaderRoute: typeof UserReportImport
      parentRoute: typeof rootRoute
    }
    '/users/new': {
      id: '/users/new'
      path: '/new'
      fullPath: '/users/new'
      preLoaderRoute: typeof UsersNewImport
      parentRoute: typeof UsersImport
    }
    '/admins/$userId/edit': {
      id: '/admins/$userId/edit'
      path: '/$userId/edit'
      fullPath: '/admins/$userId/edit'
      preLoaderRoute: typeof AdminsUserIdEditImport
      parentRoute: typeof AdminsImport
    }
    '/users/$userId/edit': {
      id: '/users/$userId/edit'
      path: '/$userId/edit'
      fullPath: '/users/$userId/edit'
      preLoaderRoute: typeof UsersUserIdEditImport
      parentRoute: typeof UsersImport
    }
  }
}

// Create and export the route tree

interface AdminsRouteChildren {
  AdminsNewRoute: typeof AdminsNewRoute
  AdminsUserIdEditRoute: typeof AdminsUserIdEditRoute
}

const AdminsRouteChildren: AdminsRouteChildren = {
  AdminsNewRoute: AdminsNewRoute,
  AdminsUserIdEditRoute: AdminsUserIdEditRoute,
}

const AdminsRouteWithChildren =
  AdminsRoute._addFileChildren(AdminsRouteChildren)

interface FinancesRouteChildren {
  FinancesEditRoute: typeof FinancesEditRoute
  FinancesNewRoute: typeof FinancesNewRoute
}

const FinancesRouteChildren: FinancesRouteChildren = {
  FinancesEditRoute: FinancesEditRoute,
  FinancesNewRoute: FinancesNewRoute,
}

const FinancesRouteWithChildren = FinancesRoute._addFileChildren(
  FinancesRouteChildren,
)

interface UsersRouteChildren {
  UsersNewRoute: typeof UsersNewRoute
  UsersUserIdEditRoute: typeof UsersUserIdEditRoute
}

const UsersRouteChildren: UsersRouteChildren = {
  UsersNewRoute: UsersNewRoute,
  UsersUserIdEditRoute: UsersUserIdEditRoute,
}

const UsersRouteWithChildren = UsersRoute._addFileChildren(UsersRouteChildren)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admins': typeof AdminsRouteWithChildren
  '/finances': typeof FinancesRouteWithChildren
  '/home': typeof HomeRoute
  '/invest': typeof InvestRoute
  '/investments': typeof InvestmentsRoute
  '/login': typeof LoginRoute
  '/plan': typeof PlanRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/reports': typeof ReportsRoute
  '/users': typeof UsersRouteWithChildren
  '/admins/new': typeof AdminsNewRoute
  '/finances/edit': typeof FinancesEditRoute
  '/finances/new': typeof FinancesNewRoute
  '/user/report': typeof UserReportRoute
  '/users/new': typeof UsersNewRoute
  '/admins/$userId/edit': typeof AdminsUserIdEditRoute
  '/users/$userId/edit': typeof UsersUserIdEditRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admins': typeof AdminsRouteWithChildren
  '/finances': typeof FinancesRouteWithChildren
  '/home': typeof HomeRoute
  '/invest': typeof InvestRoute
  '/investments': typeof InvestmentsRoute
  '/login': typeof LoginRoute
  '/plan': typeof PlanRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/reports': typeof ReportsRoute
  '/users': typeof UsersRouteWithChildren
  '/admins/new': typeof AdminsNewRoute
  '/finances/edit': typeof FinancesEditRoute
  '/finances/new': typeof FinancesNewRoute
  '/user/report': typeof UserReportRoute
  '/users/new': typeof UsersNewRoute
  '/admins/$userId/edit': typeof AdminsUserIdEditRoute
  '/users/$userId/edit': typeof UsersUserIdEditRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/admins': typeof AdminsRouteWithChildren
  '/finances': typeof FinancesRouteWithChildren
  '/home': typeof HomeRoute
  '/invest': typeof InvestRoute
  '/investments': typeof InvestmentsRoute
  '/login': typeof LoginRoute
  '/plan': typeof PlanRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/reports': typeof ReportsRoute
  '/users': typeof UsersRouteWithChildren
  '/admins/new': typeof AdminsNewRoute
  '/finances/edit': typeof FinancesEditRoute
  '/finances/new': typeof FinancesNewRoute
  '/user/report': typeof UserReportRoute
  '/users/new': typeof UsersNewRoute
  '/admins/$userId/edit': typeof AdminsUserIdEditRoute
  '/users/$userId/edit': typeof UsersUserIdEditRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admins'
    | '/finances'
    | '/home'
    | '/invest'
    | '/investments'
    | '/login'
    | '/plan'
    | '/profile'
    | '/register'
    | '/reports'
    | '/users'
    | '/admins/new'
    | '/finances/edit'
    | '/finances/new'
    | '/user/report'
    | '/users/new'
    | '/admins/$userId/edit'
    | '/users/$userId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admins'
    | '/finances'
    | '/home'
    | '/invest'
    | '/investments'
    | '/login'
    | '/plan'
    | '/profile'
    | '/register'
    | '/reports'
    | '/users'
    | '/admins/new'
    | '/finances/edit'
    | '/finances/new'
    | '/user/report'
    | '/users/new'
    | '/admins/$userId/edit'
    | '/users/$userId/edit'
  id:
    | '__root__'
    | '/'
    | '/admins'
    | '/finances'
    | '/home'
    | '/invest'
    | '/investments'
    | '/login'
    | '/plan'
    | '/profile'
    | '/register'
    | '/reports'
    | '/users'
    | '/admins/new'
    | '/finances/edit'
    | '/finances/new'
    | '/user/report'
    | '/users/new'
    | '/admins/$userId/edit'
    | '/users/$userId/edit'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminsRoute: typeof AdminsRouteWithChildren
  FinancesRoute: typeof FinancesRouteWithChildren
  HomeRoute: typeof HomeRoute
  InvestRoute: typeof InvestRoute
  InvestmentsRoute: typeof InvestmentsRoute
  LoginRoute: typeof LoginRoute
  PlanRoute: typeof PlanRoute
  ProfileRoute: typeof ProfileRoute
  RegisterRoute: typeof RegisterRoute
  ReportsRoute: typeof ReportsRoute
  UsersRoute: typeof UsersRouteWithChildren
  UserReportRoute: typeof UserReportRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminsRoute: AdminsRouteWithChildren,
  FinancesRoute: FinancesRouteWithChildren,
  HomeRoute: HomeRoute,
  InvestRoute: InvestRoute,
  InvestmentsRoute: InvestmentsRoute,
  LoginRoute: LoginRoute,
  PlanRoute: PlanRoute,
  ProfileRoute: ProfileRoute,
  RegisterRoute: RegisterRoute,
  ReportsRoute: ReportsRoute,
  UsersRoute: UsersRouteWithChildren,
  UserReportRoute: UserReportRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/admins",
        "/finances",
        "/home",
        "/invest",
        "/investments",
        "/login",
        "/plan",
        "/profile",
        "/register",
        "/reports",
        "/users",
        "/user/report"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/admins": {
      "filePath": "admins.tsx",
      "children": [
        "/admins/new",
        "/admins/$userId/edit"
      ]
    },
    "/finances": {
      "filePath": "finances.tsx",
      "children": [
        "/finances/edit",
        "/finances/new"
      ]
    },
    "/home": {
      "filePath": "home.tsx"
    },
    "/invest": {
      "filePath": "invest.tsx"
    },
    "/investments": {
      "filePath": "investments.tsx"
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/plan": {
      "filePath": "plan.ts"
    },
    "/profile": {
      "filePath": "profile.tsx"
    },
    "/register": {
      "filePath": "register.tsx"
    },
    "/reports": {
      "filePath": "reports.tsx"
    },
    "/users": {
      "filePath": "users.tsx",
      "children": [
        "/users/new",
        "/users/$userId/edit"
      ]
    },
    "/admins/new": {
      "filePath": "admins.new.tsx",
      "parent": "/admins"
    },
    "/finances/edit": {
      "filePath": "finances.edit.tsx",
      "parent": "/finances"
    },
    "/finances/new": {
      "filePath": "finances.new.tsx",
      "parent": "/finances"
    },
    "/user/report": {
      "filePath": "user.report.tsx"
    },
    "/users/new": {
      "filePath": "users.new.tsx",
      "parent": "/users"
    },
    "/admins/$userId/edit": {
      "filePath": "admins.$userId.edit.ts",
      "parent": "/admins"
    },
    "/users/$userId/edit": {
      "filePath": "users.$userId.edit.tsx",
      "parent": "/users"
    }
  }
}
ROUTE_MANIFEST_END */
